# Generated by Django 3.2 on 2022-08-14 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_product_favourites'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFavourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordfreq', models.IntegerField(choices=[(1, 'One Week'), (2, 'Two Week'), (3, 'Three Weeks'), (4, 'Four Weeks')])),
                ('favcat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('favprod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
    ]
