# Generated by Django 3.2 on 2022-08-14 12:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_product_favourites'),
        ('favourites', '0002_auto_20220814_1241'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductFavourites',
            new_name='ProductFavourite',
        ),
    ]
