# Generated by Django 3.2 on 2022-08-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0003_rename_productfavourites_productfavourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfavourite',
            name='order_frequency',
            field=models.IntegerField(choices=[(1, 'One Week'), (2, 'Two Week'), (3, 'Three Weeks'), (4, 'Four Weeks')], null=True),
        ),
    ]
