# Generated by Django 3.2 on 2022-05-24 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_rename_phone_nbr_order_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_nbr',
            new_name='order_number',
        ),
    ]
